# Generated by Django 3.0.6 on 2020-05-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('git_name', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'verbose_name': '任务',
                'ordering': ['create_time'],
            },
        ),
    ]
