# Generated by Django 3.0.6 on 2020-05-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0002_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('blog_num', models.IntegerField(default=0)),
                ('public_repo_num', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('following_num', models.IntegerField(default=0)),
                ('follower_num', models.IntegerField(default=0)),
                ('public_gists_num', models.IntegerField(default=0)),
                ('task_id', models.CharField(db_index=True, max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='tasks',
            name='git_name',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
