# Generated by Django 3.0.6 on 2020-05-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0005_auto_20200524_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='email',
            field=models.EmailField(default='None', max_length=128),
        ),
    ]
