# Generated by Django 3.0.6 on 2020-05-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0007_auto_20200524_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeskResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('blog', models.CharField(max_length=64)),
                ('public_repo_num', models.IntegerField(default=0)),
                ('following_num', models.IntegerField(default=0)),
                ('follower_num', models.IntegerField(default=0)),
                ('public_gists_num', models.IntegerField(default=0)),
                ('task_id', models.CharField(db_index=True, max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='Results',
        ),
    ]
